(define (make-account balance true-passwd)
  (define (call-the-cops)
    (printf "call 110!~N"))
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient balance"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define incorrect-times 0)
  (lambda (passwd m)
    (if (not (equal? passwd true-passwd))
      (begin
        (set! incorrect-times (+ incorrect-times 1))
        (when (>= incorrect-times 7)
          (call-the-cops))
        (lambda args "Incorrect password"))
      (begin 
        (set! incorrect-times 0)
        (cond ((equal? m 'withdraw) withdraw)
              ((equal? m 'deposit) deposit)
              (else 
                (error "Unknown request")))))))

(define w1 (make-account 100 '123))
((w1 '123 'withdraw) 5)
((w1 'wrong 'withdraw) 5)
((w1 'wrong 'withdraw) 5)
((w1 'wrong 'withdraw) 5)
((w1 'wrong 'withdraw) 5)
((w1 'wrong 'withdraw) 5)
((w1 'wrong 'withdraw) 5)
((w1 'wrong 'withdraw) 5)

